easy_transformer/hook_points.py
They were sometimes getting registered as fwd.
I didn't try running this (just noticed it on GH), but seems obviously right.
=> Fix bug in bwd hooks

EasyTransformer_Demo.ipynb, Interpreting_Sorting_Demo.ipynb, easy_transformer/EasyTransformer.py, easy_transformer/EasyTransformerConfig.py, easy_transformer/components.py
Fixed a bug in the Mistral model code - turns out they scale attention down even further pre softmax by 1/(layer_index + 1) for numerical stability reasons (trained in FP16 I think?). That took me _so_ long to trace down.....
=> Fixed infuriating Mistral bug

easy_transformer/hook_points.py
The commit ['Added run_with_cache'](https://github.com/neelnanda-io/Easy-Transformer/commit/1d05765937e238abfd7b75ed05ca6f467fffe7f2) caused an ImportError when importing EasyTransformer on Google Colab.
```
!pip install git+https://github.com/neelnanda-io/Easy-Transformer.git
from easy_transformer import EasyTransformer
```
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-3-eaa29a0c1bcc>](https://localhost:8080/#) in <module>
----> 1 from easy_transformer import EasyTransformer
1 frames
[/usr/local/lib/python3.7/dist-packages/easy_transformer/__init__.py](https://localhost:8080/#) in <module>
----> 1 from . import hook_points
2 from . import EasyTransformer
3 from . …
```
=> Remove _quantize_ondevice_ptq_dynamic import

.github/workflows/todo-workflow.yaml, .gitignore, EasyTransformer_Demo.ipynb
I added an integration to search things that [look like TODO comments](https://github.com/marketplace/actions/track-todo-action) and convert them into GitHub issues.
Notably, this integration failed to find the TODO comment inside EasyTransformer_Demo.ipynb. I [manually created an issue for this one](https://github.com/neelnanda-io/Easy-Transformer/issues/55). 
Maybe-someday I'll write my own integration that does something dumber/more robust in that it just looks for the word TODO.
=> Add GitHub actions

Exploratory_Analysis_Demo.ipynb, easy_transformer/EasyTransformer.py
Previously, loading in any OPT model and doing `model.to_token("Hello")` would give the tensor `[2, 2, 5625]`. This fixes that change
=> Fix opt tokenizer

easy_transformer/train.py
There's a quote in this very file, "Weight decay in Adam is implemented badly, so use AdamW instead", so I figured we ought to change the default.
=> Use AdamW optimizer by default.

easy_transformer/EasyTransformer.py
I searched the file for `num_return_sentences`: there are no other occurrences.
=> Remove unused parameter from `generate`

easy_transformer/utils.py
It was assumed that tokes(str1+str2) == tokens(str1)+tokens(str2), but this is not always the case
=> utils.test_prompt tokenization bugfix

easy_transformer/utils.py
Use case: I have long prompts that I'm testing on two models. I want to see top k predictions for both, but I don't need to see long tokenized prompt twice.
=> added print_tokenized flag to utils.test_prompt

poetry.lock, pyproject.toml
Paperspace installs a much older version by default.
=> Reduce torch required version

transformer_lens/HookedTransformer.py, transformer_lens/utils.py
Added a sample_datapoint method to get a random data point from a model's training distribution. Added supporting methods to load in various 10K element datasets in `utils.get_dataset`, and `HookedTransformer.load_sample_training_dataset`. 
Also added a truncation option to `to_tokens`, which defaults to True. **This is a minor breaking change**, but I would be surprised if anyone's using this in a way that breaks things? (Sorry if I'm wrong!). And IMO this is correct behaviour - `to_tokens` is designed to be a wrapper around model inputs, so we want to make sure it gives inputs that don't break things!
Example usage:
```
m = HookedTransformer.from_pretrained("gpt2-xl")
sample_tokens = m.sample_datapoint(tokenize=True)
log_probs = m(sample_tokens).log_softmax(dim=-1)
```
We can feed this …
=> Added sample_datapoint, get_dataset and token truncation by default

transformer_lens/loading_from_pretrained.py
Small PR to add finetuned versions of `solu-1l` and `solu-4l` on 4.8B tokens of wikipedia (previously trained on 22B tokens of 80% C4 and 20% python code)
Called `solu-1l-wiki` and `solu-4l-wiki`, comes with 163 checkpoints taken roughly  exponentially spaced during fine tuning.
=> Added code to load in fine-tuned versions of SoLU 1L and SoLU 4L on 4.8B tokens of wikipedia

transformer_lens/HookedTransformer.py, transformer_lens/tests/test_tokenizer_special_tokens.py
This addresses issue https://github.com/neelnanda-io/TransformerLens/issues/153.
For reasons that are unclear to me, the PreTrainedtokenizer for Facebook OPT automatically prepends `</s>` to OPT prompts, unless the tokenizer call sets `add_special_tokens=False`. This has no effect for the GPT tokenizer.
*I Am not sure* if this breaks things for other models, in which case we'd want to do `add_special_tokens='opt' in self.tokenizer.name` but would prefer to avoid that if possible.
=> Fix OPT BOS Prepending issue

transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/tests/test_hook_tokens.py
Added `hook_tokens` option to the config object (default value is `False`). If this is true, then we call:
```python
tokens = self.hook_tokens(tokens)
```
before applying the embedding, in our HookedTransformer's forward pass.
---
The files that were edited were:
* `HookedTransformerConfig` (to add `hook_tokens` as a default argument, and add a docstring to the config object)
* `HookedTransformer` (in 2 places - once to define the hooks, and once to apply them if they exist)
---
This is useful when we combine it with permanent hooks to e.g. implement certain types of model architecture. Here is an example of how we can use this feature to turn a bidirectional transformer into one which applies a mask to the padding tokens at each attention layer, in the style of BERT:
```python
def …
```
=> add hook tokens

transformer_lens/HookedTransformer.py
There's no easy way to disable tqdm with context managers (afaik!), and patching tqdm around generate calls where one wants to avoid the tqdm output is tedious.
Not sure "verbose" is the best name for this flag as it's really more of a `show_progress`, but might be better to be generic and imprecise.
=> Add `verbose` flag to disable tqdm on `model.generate(...)`

.github/workflows/checks.yml, tests/acceptance/test_transformer_lens.py
Add [branch coverage](https://coverage.readthedocs.io/en/7.1.0/branch.html). Closes #189.
Note: I had to add a dummy commit and revert it to trigger github actions, in order to ensure that the reports are being printed correctly.
At a glance, this produces the following changes in the report:
* New columns: `Branch` and `BrPart`
* Modified percentages in `Cover` column
* `Missing` column seems to have been modified to reflect branches rather than lines 
One thing that is unclear to me from the report is how the coverage percentage is actually computed. It looks like we could get more information on branch coverage by using the html, xml or json report types, but this would take more effort to set up. [Quote from cov docs](https://coverage.readthedocs.io/en/7.1.0/branch.html#how-to-measure- …
=> Configure coverage reports to measure branch coverage

pyproject.toml
Silence warnings in test output. 
I think these warnings are caused because pandas is using `LooseVersion` from `numpy.distutils`, which is [deprecated](https://numpy.org/doc/stable/reference/distutils.html).
```python
❯ poetry run pytest transformer_lens/tests
================================== test session starts ===================================
platform darwin -- Python 3.9.16, pytest-7.2.1, pluggy-1.0.0
rootdir: /Users/rusheb/code/TransformerLens
plugins: jaxtyping-0.2.12, typeguard-2.13.3, cov-4.0.0, anyio-3.6.2
collected 29 items
transformer_lens/tests/test_cache_hook_names.py .                                  [  3%]
transformer_lens/tests/test_d_vocab.py ....                                        [ 17%]
transformer_lens/tests/test_hook_tokens.py . …
```
=> Silence DeprecationWarning for distutils

.github/workflows/gh-pages.yml
GH-Pages workflow is broken due to Poetry release last line (https://pypi.org/project/poetry/#history) 
This should fix the issue by going back to the previous version. Only setting it for gh-pages as regular workflow seems fine. Hopefully this is just a temporary measure. 
=> set specific poetry version

setup.py
Remove `torchtyping` from `install_requires` in `setup.py`.
I'm not sure, but I think this is no longer needed. As far as I can see, this dependency was removed from `pyproject.toml` in 30ed77338f54b765a80d7e12d8fa24b5281c3145 (PR #171).
No issue.
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have made corresponding changes to the documentation~~
- ~~I have added tests that prove my fix is effective or that my feature works~~
=> Remove torchtyping from install_requires

tests/unit/test_hooks.py, transformer_lens/HookedTransformer.py, transformer_lens/hook_points.py
This would let you run the model like this:
```python
with model.hooks(fwd_hooks=hooks):
hooked_loss = model(text, return_type="loss")
```
A quick example:
```python
from transformer_lens.evals import sanity_check, induction_loss
from transformer_lens.HookedTransformer import HookedTransformer
import transformer_lens.utils as utils
model = HookedTransformer.from_pretrained('gpt2-small')
text = "The quick brown fox jumps over the lazy dog"
def head_ablation_hook(value, hook):
value[:, :, 8, :] = 0.
return value
hooks = [(utils.get_act_name("v", 0), head_ablation_hook)]
print("Normal induction loss", induction_loss(model))
with model.hooks(fwd_hooks=hooks):
print('Hooked induction loss', induction_loss(model))
normal_loss = model(text, return_type="loss")
print(f"Normal loss: …
```
=> Add context manager

tests/acceptance/test_activation_cache.py, transformer_lens/ActivationCache.py
This PR addresses #209 making the following changes:
- add optional apply_ln param to accumulated_resid and decompose_resid to automatically apply layernorm to corresponding stack
- adds 2 basic tests to sanity check these both work as intended
- Corrects a typo in get_full_resid_decomposition doc string
- [ x] New feature (non-breaking change which adds functionality)
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
=> Add apply_ln param to accumulated_resid and decompose_resid

docs/source/content/tutorials.md
Noticed a small typo in `tutorials.md` so I changed "tutotial" -> "tutorial"
Fixes # (issue) - no linked issue
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
=> Small spelling mistake fix

transformer_lens/hook_points.py
Fixes docstrings in the `hook_points.py` file.
- Fixes formatting for `run_with_hooks` and `run_with_cache`
- Adds code example for `hooks` context manager
- Converts comments in `HookPoint` to docstrings.
=> Fix docstrings

tests/unit/factored_matrix/test_multiply_by_vector.py, transformer_lens/FactoredMatrix.py
This PR fixes #225 by squeezing the correct dimension of a vector x FactoredMatrix multiplication result. As @rusheb mentions, there is a risk of breaking code for anyone who is currently assuming the output to have shape (1, ...). (Although I think this is realistically a pretty small risk?)
- [x ] Bug fix 
- [x ] Breaking change (fix that would cause existing functionality to not work as expected)
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
=> Squeeze 0th dim in vector FactoredMatrix multiply

tests/acceptance/test_activation_cache.py, transformer_lens/ActivationCache.py
Previously I added an apply_ln parameter to accumulated_resid and decompose_resid in PR #220 to address issue #209 . After using them, I'm noticing it's also natural to make an analogous call to stack_head_results and stack_neuron_results (like when doing direct logit attribution). This PR adds the same functionality to stack_head_results and stack_neuron_results so they are all consistent. I also deleted a line from the stack_head_results doc string which doesn't seem true.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- …
=> Add apply_ln to stack_head_results and stack_neuron_results

transformer_lens/patching.py
There are a handful of patching helper functions with similar names, so I sometimes read the code to determine which one I should be using and what the inputs / outputs are. I think this can be a hassle because the partial functions are not documented, so I need to jump between them and generic_activation_patch to figure out how they work. To help solve this, I added docstrings for a bunch of patching helper functions. 
- [x ] This change requires a documentation update
- [x ] I have made corresponding changes to the documentation
- [x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
=> Improve patching docs

demos/Main_Demo.ipynb
In the main demo update the outdated link to the exploratory analysis demo in the activation patching section and fix the shape typo in the transformer architecture section.
=> fix outdated link and shape typo in main demo

demos/Exploratory_Analysis_Demo.ipynb
In the exploratory analysis demo, update the outdated link to the Main_Demo in the introduction section and Activation_Patching_in_TL_Demo in the activation patching section.
=> fix outdated link in Exploratory Analysis Demo

tests/acceptance/test_transformer_lens.py, transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py
Currently it is not possible to load `redwood_attn_2l` with `from_pretrained` because the `fold_ln` parameter needs to be rewritten to `False` in two places, and it is only rewritten in one place. Similarly, centering weights needs to be handled properly. 
Regarding the checklist, I think the warnings describe what is happening, but lmk if this is not clear.
Fixes [# (issue)](https://github.com/neelnanda-io/TransformerLens/issues/267)
- [ x  ] Bug fix (non-breaking change which fixes an issue)
- [ x  ] New feature (non-breaking change which adds functionality)
- [   ] I have commented my code, particularly in hard-to-understand areas
- [   ] I have made corresponding changes to the documentation
- [   ] My changes generate no new warnings
- [ x …
=> Fix `from_pretrained` with `redwood_attn_2l`

tests/acceptance/test_transformer_lens.py, transformer_lens/loading_from_pretrained.py
Description
Added load_mingpt_weights function in loading_from_pretrained, integrated with loading pipeline
Type of change
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update
Issues:
Loading seems broken when loading without ln_fold=False, center_writing_weights=False, center_unembed=False; achives ~1e-12 MSE on outputs with the above config, ~1e-2 without.
=> Baidicoot main - Implemented functionality for loading mingpt-style models off HF (e.g. othello-gpt)  

tests/acceptance/test_hooked_transformer.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
Closes #289 by adding the [various tiny-stories models](https://huggingface.co/datasets/roneneldan/TinyStories) from Hugginface to TransformerLens.
Also extends the hooked transformer acceptence test to check that our 33M version generates output similar to the Hugginface output that can be generated with [this](https://pastebin.com/md4E3Gru) snippet.
=> Add tiny stories

tests/acceptance/test_hooked_encoder.py, tests/acceptance/test_hooked_transformer.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
The issue is about adding the possibility to have a custom cache directory different from the HuggingFace default directory, with the from_pretrained `cache_dir` argument. The solution is more generic as it is designed to allow the use of Hugging Face's from_pretrained arguments in general. I didn't add a test for the parameter cache_dir, because it would be too long to execute if you have to re-download the model each time, but I tested it manually.
This should be backward-compatible, because it mainly adds new possible arguments.
Fixes #288
=> from_pretrained custom parameters (#288)

transformer_lens/hook_points.py
This adds a better `__name__` attribute to `full_hook`s that can make debugging easier.
Makes progress on https://github.com/neelnanda-io/TransformerLens/issues/297 - the snippet at the bottom there is the best example of how this may help
- [ x ] New feature (non-breaking change which adds functionality)
N/A
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
i) there …
=> Add better `__name__` annotation to `full_hook`s

transformer_lens/HookedTransformer.py, transformer_lens/evals.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
Small fixes, mainly :
- `convert_state_dict` was not used and not working
- `select_compatible_kwargs` was not set to be ignored by Sphinx (=> `_select_compatible_kwargs`)
- `GPTJForCausalLM` was duplicated in `model_dataset_map`
- Wrong description for `make_pile_data_loader`
No related issue.
Let me know if you prefer to always have a related open issue, but for such small fixes it feels to me quite bureaucratic and inefficient. 
Also, I hesitate to open an issue for adding a leading "_" everywhere relevant for Sphinx to ignore these functions, in order to simplify the documentation. For example, there are many functions in `loading_from_pretrained.py` that are useless and potentially confusing for end users. Do you agree ?
=> Multiple minor corrections

tests/acceptance/test_hooked_encoder.py, transformer_lens/HookedEncoder.py
- Move `self.to(device)` later in the file, after parameters have been initialised
- Move majority of tests to the CPU, and add a specific test for the GPU
Fixes #306 
=> Fix bug: HookedEncoder not being moved to GPU

tests/unit/test_hooks.py, transformer_lens/HookedTransformer.py, transformer_lens/hook_points.py
This PR allows users to prepend hooks before all other hooks, and a test of this.
This is implemented in the same way that PyTorch 2.0 does this: search https://github.com/pytorch/pytorch/blob/bf52d570d9be0167501cd6a206b7e262e6d3860c/torch/nn/modules/module.py for "prepend"
I have checked that the test and black pass locally. I think that the main failures are not related.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have not …
=> Add prepend option to `model.add_hook`

tests/acceptance/test_activation_cache.py, tests/unit/test_cache_hook_names.py, transformer_lens/HookedTransformer.py, transformer_lens/components.py
Currently, there's no clean way to manipulate the output of one attention head into a future MLP in our transformer model. This is because editing hook_resid_mid affects the residual stream beyond the MLP too, as it is used in the computation of both resid_mid and resid_post.
This PR introduces a new `hook_mlp_in` `HookPoint` that allows modification of the input to an MLP. 
It adds a test too. I also commented two places I found some repeated code, I'm happy to improve this too if wanted.
This HookPoint will be enabled by default. Initially, we were concerned about potential memory bloat and potential backwards compatibility issues with old code that expects a specific set of keys in an ActivationCache. However, upon further investigation, it was found that since the resid_mid and …
=> Add `hook_mlp_in`

docs/README.md, docs/source/conf.py, docs/source/transformer_lens.rst, docs/source/transformer_lens.utilities.rst, tests/unit/test_head_detector.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
The aim is to ignore in the documentation some functions that are not useful for end users, to reduce the quantity of superfluous information. At first I was proposing to add an underscore (e.g. `make_model_alias_map` => `_make_model_alias_map`), but I finally adopted the safer approach proposed by @ArthurConmy of using the `field exclude-members` in `autodoc_default_options` to specify functions to ignore. It is then indeed not displayed in Sphinx.
I reverted one of the modifications of my last PR (`_select_compatible_kwargs` => `select_compatible_kwargs`) to be consistent everywhere.
The list of functions to ignore is debatable. I didn't add any class method (although `fill_missing_keys` is a function in `loading_from_pretrained.py`, but also a method of `HookedTransformer` which is …
=> Ignore some functions in the documentation (#310)

transformer_lens/HookedTransformer.py
You can't `refactor_factored_attn_matrices` with rotary models so error here.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
I don't think we need a test for this because that would require loading in a `pythia-70m` which seems an annoying increase to test speed, so this is ready for review
=> Add assertion to refactor_factored_attn_matrices

tests/unit/test_svd_interpreter.py
Fixes #328 
1. Moves tensors to CPU before checking with `assert`
2. Checks absolute value of SVD vectors instead of the vectors themselves.
As I mentioned in #328, SVD is not numerically stable so different hardware gives different results. From the pytorch docs: `This non-uniqueness is caused by the fact that multiplying any pair of singular vectors u_k, v_k by -1 in the real case produces another two valid singular vectors of the matrix.` So I think comparing `v.abs()` in the tests should get around this issue.
I have run the tests on M1 Mac, Ubuntu with GPU, Ubuntu without GPU.
=> Fix svd tests on GPU

transformer_lens/hook_points.py, transformer_lens/loading_from_pretrained.py
See discussion in #290
Thanks @rusheb for the testing script and for finding the circular reference.
This PR:
1. Removes circular reference in `HookedRootModule`'s `setup`.
2. Sets `requires_grad=False` before copying weights from HuggingFace models.
Running @rusheb's testing script
```python
from transformer_lens import HookedTransformer
from tqdm import tqdm
for _ in tqdm(range(10)):
model = HookedTransformer.from_pretrained("gpt2-small", device="cpu")
```
```
Profiler reports peak tracked memory usage
No changes:          17551.0 MiB
Only fix reference:  12416.2 MiB
Only fix gradient:   7342.4 MiB
Fix both:            2207.5 MiB
```
This fix does not help with GPU memory use.
=> Reduce memory use when loading model

tests/acceptance/test_hooked_transformer.py, tests/unit/test_svd_interpreter.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/utils.py
Improves model loading to GPU.
Instead of old process:
`init model -> move to GPU -> get state_dict -> move state dict to GPU -> process state dict-> load state dict`
We have new process:
`init model -> get state_dict -> process state dict -> load state dict -> move model to GPU`
This results in a 2x reduction in GPU memory use when loading from pretrained.
Addresses #252 
Also fixes #329 
Other things to be aware of:
1. I have removed the `move_state_dict_to_device` option from `load_state_dict`.
2. I’ve increased ATOL in `test_svd_interpreter` from 1e-4 to 2e-4.
Expected:
`[[[0.5097, 0.5389, 0.7906, 0.7178]], [[0.5076, 0.5350, 0.7674, 0.7106]]]`
New:
`[[[0.5098, 0.5390, 0.7907, 0.7178]], [[0.5077, 0.5351, 0.7675, 0.7107]]]`
The values are off by at most 1e-4. I think this is acceptable …
=> Halve GPU memory when loading

transformer_lens/hook_points.py
These lines don't work in the intended way when `names_filter` is a string because redefining names_filter and using it in the lambda expression doesn't play nicely (CC GPT-4 or "late binding" in Python docs)
More generally I think the type for `NamesFilter` should also contain `str`s (`Sequence[str]` isn't really accurate) and the documentation of `add_caching_hooks` should mention that `names_filter` can be a string. Happy to merge this fix as-is or implement those two docs changes on top of this
=> `names_filter` bug fix

transformer_lens/components.py
The comment documenting hook_result shape seems wrong. This PR fixes it.
=> Fix hook_result shape comment

tests/acceptance/test_hooked_encoder.py, tests/acceptance/test_hooked_transformer.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/components.py, transformer_lens/head_detector.py, transformer_lens/loading_from_pretrained.py, transformer_lens/past_key_value_caching.py, transformer_lens/utilities/devices.py, transformer_lens/utils.py
`HookedTransformerKeyValueCacheEntry` wasn't compatible with other dtypes, so the argument `past_kv_cache_entry` wasn't working.
There is also an optimization. Instead of initializing the model in torch.float32 and then converting it to the desired dtype, we now directly initialize the model layers in the desired dtype.
The attribute `dtype` was added to the configuration with the default value torch.float32. I hope this is ok. It's practical to have access to it from anywhere.
Also added a test for 8 bits loading, which is skipped if there is no GPU.
Fixes # 104
=> Support for reduced precision (#104)

docs/source/transformer_lens.rst
The docs have drifted out of sync. (This diff was generated by https://github.com/neelnanda-io/TransformerLens/pull/338 and the check passed when pushed to that branch.)
Documentation update.
=> Fix API docs

transformer_lens/HookedTransformerConfig.py, transformer_lens/utilities/devices.py
Fixes #356 by removing the device check in `HookedTransformerConfig`.
This assert didn’t make sense as it should be possible to first load the model on CPU and then move it to devices.
=> Remove n_devices assert in config

tests/unit/factored_matrix/test_multiply_by_scalar.py, transformer_lens/FactoredMatrix.py
Implemented __mul__ and __rmul__ for Factoredmatrix to support scalar multiplication with *.
Supports floats, ints and single-element Tensors.
Approriate error messages and test are in place.
Fixes #348 
=> Scalar multiplication

transformer_lens/components.py
This PR fixes the bug in the calculation of rotary embedding, which affects the performance of the models that use rotary embedding other than llama and gpt-neo, e.g., gpt-j.
https://github.com/neelnanda-io/TransformerLens/blob/bf5ed27cef2a566377151228acd5c7eb1b641195/transformer_lens/components.py#L697
```
if (
self.cfg.original_architecture
in ["GPTNeoXForCausalLM", "LlamaForCausalLM"],  # the , at the end causes the bug
):
n = x.size(-1) // 2
rot_x[..., :n] = -x[..., n:]
rot_x[..., n:] = x[..., :n]
else:
rot_x[..., ::2] = -x[..., 1::2]
rot_x[..., 1::2] = x[..., ::2]
```
Let's say that `self.cfg.original_architecture = 'GPTJForCausalLM'`. Then, the desired behaviour is to execute the `else` branch because `self.cfg.original_architecture` is not in `["GPTNeoXForCausalLM", …
=> Fix bug in rotary embedding for models other than llama and gpt-neo

tests/unit/factored_matrix/test_get_item.py, transformer_lens/FactoredMatrix.py
The function `_convert_to_slice` was added recently, which causes indexing with elements to work (previously this didn't work). But when this change was made, it caused indexing with sequences to work. 
The solution is to make `_convert_to_slice` only alter integer elements of the index.
To further explain, `_convert_to_slice` will take an integer like `1` and convert it into the slice `slice(1, 2)`. This is good because now the indexed tensors `A` and `B` have the correct number of dimensions (i.e. they don't lose a dimension). But this isn't how we should treat things like `t.tensor([0, 1, 2])` when they're used as an index, because they're already in the correct form for indexing (i.e. indexing with them won't delete a dimension).
I've now added tests to …
=> Fix FactoredMatrix bug

tests/unit/test_prepend_bos.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py
Remove the hard-coded part that determines the value to be passed to `tokenizer(add_special_tokens=...)` in `to_tokens()` that is prone to bugs like #369.
Automatically infer the value to be passed as follows:
```python3
add_special_tokens = not (
len(self.tokenizer("")["input_ids"]) > 0
and self.tokenizer("")["input_ids"][0] == self.tokenizer.bos_token_id
)
```
Set this value as `add_special_tokens` in `HookedTransformerConfig` when `set_tokenizer()` is called. The value is set to `None` until `set_tokenizer` is called.
When calling `to_tokens()`, do a simple sanity check by ensuring `model.cfg.add_special_tokens` is not `None` to better ensure that the tokenizer is set using `set_tokenizer()` and thus `add_special_tokens` is set correctly.
Fixes #369
```python3
model = …
```
=> Fix to automatically infer add_special_tokens for tokenizer

transformer_lens/HookedTransformer.py, transformer_lens/components.py, transformer_lens/utils.py
Added a hook for the linear input of a gated MLP. Called `hook_pre_linear`
Current structure:
There are 3 weight matrices for the MLP, W_gate, W_in, and W_out
Given an input resid_mid, we compute 
hook_pre = resid_mid @ W_gate
hook_pre_linear = resid_mid @ W_in
hook_post = act_fn(hook_pre) * hook_pre_linear + b_in
hook_mlp_out = hook_post @ W_out + b_out
=> Added gated MLP Hooks

transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/components.py
Removes `@lru_cache` decorator from weight methods.
Fixes https://github.com/neelnanda-io/TransformerLens/issues/363
=> Remove lru caching of weights

transformer_lens/HookedTransformer.py, transformer_lens/components.py
Previously `hook_mlp_in` wasn't implemented in parallel attention/MLP models. Oops! I even remembered to add this to BERT...
I also added a check that `hook_mlp_in` is not being used with attention only models.
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> Implement `hook_mlp_in` for parallel attention/MLP models

tests/unit/test_start_at_layer.py, transformer_lens/HookedTransformer.py
- Add `start_at_layer` to HookedTransformer forward function.
- Pull out the embedding step into a seperate function to enable this.
- Add parameters `tokens`, `shortformer_pos_embed` and `left_attention_mask` to forward function as these outputs of the embed step are sometimes required.
- Add tests for `start_at_layer`.
Sometimes I want to run patching experiments where I know all the patches are in the last few layers. In this case, I can cache the result of the earlier layers for improved performance.
=> Add start_at_layer parameter to HookedTransformer

tests/unit/test_attention_mask.py, transformer_lens/HookedEncoder.py, transformer_lens/components.py
Supersedes https://github.com/neelnanda-io/TransformerLens/pull/319. Just copied the changes + the final requested change.
From the other PR description:
"Fixes https://github.com/neelnanda-io/TransformerLens/issues/318 - In pythia-70m, attn_scores can get below -1e5 (for some reason...). Masked attn scores are set to -1e5, so this makes the model attend outside the mask! This is dumb, and so I set things to -torch.inf instead. It's still registered as a buffer so should move to device + dtypes accordingly"
=> fix: Set IGNORE value in mask to -torch.inf

tests/unit/test_only_tokenizer.py, tests/unit/test_prepend_bos.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/utils.py
This PR ensures that the `tokenizer` used by the model is initialized with `add_bos_token=True`.
Previously, the tokenizer that  does not prepend bos was used as default. When we wanted to prepend a bos token to the input, we manually added it to the input, e.g., `tokenizer.bos_token + input`. However, this resulted in a bug for LLaMA tokenizers because they behave differently when the bos token is manually prepended and when it is automatically prepended by the tokenizer (https://github.com/neelnanda-io/TransformerLens/issues/373#issuecomment-1701017935).
It is necessary to ensure that the tokenizer is initialized with `from_pretrained(add_bos_token=True)` because `add_bos_token` cannot be dynamically controlled after initialization …
=> Fix llama tokenization issue by using tokenizer initialized with add_bos_token=True

transformer_lens/ActivationCache.py, transformer_lens/HookedTransformer.py
Convert ActivationCache and HookedTransformer docstrings/comments to the consistent Google Python Style Guide.
Note the only changes made are:
- Make sure docstrings have titles (and they end in a full stop).
- Put all args under "Args:" (some were missing this section title so they didn't show on the Sphinx docs)
- Some very minor spelling mistakes/moving titles to the imperative tense.
- Use rewrap to make all the comments the same length (100, as per Pylint config in the project)
There are still other things missing (e.g. sometimes args are not documented) but it's a good start.
=> Move towards consistent commenting/docstring style

.github/workflows/gh-pages.yml
We shouldn't need to run poetry lock here (the lockfile is already checked in).
=> Speed up docs generation

transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py
A cosmetic change to add a dtype option on from_pretrained. Previously you could set torch_dtype and it would work, but this was not documented (and I didn't realise it until implementing a PR for mixed precision lol)
=> Added explicit dtype option

pyproject.toml
This is slowing down formatting checks where Poetry is installing into a local .venv folder (as it also formats all Python dependencies).
=> Remove .venv from formatting checks

.vscode/settings.json
Small tweak to reduce reliance on `make format`.
=> Add auto-organise imports on save in VsCode

transformer_lens/HookedTransformer.py
Several types are given defaults but not marked as optional.
Also closes #62
=> Fix optional types in HookedTransformer

tests/unit/test_kv_cache.py, tests/unit/test_left_padding.py, tests/unit/test_start_at_layer.py, tests/unit/test_utils.py, transformer_lens/HookedTransformer.py, transformer_lens/components.py, transformer_lens/past_key_value_caching.py, transformer_lens/utils.py
- Support passing in multiple tokens when using `past_kv_cache`.
- Change `left_attention_mask` to `attention_mask`. Update `apply_causal_mask` and `apply_rotary` to support arbitrary masking (and do it faster). This means that caching 'just works' regardless of padding. So you can, for example, cache keys and values for a batch of tokens and then run a left padded batch of tokens, and the padding tokens in the middle of the sequence will be ignored.
- Add tests for `past_kv_cache`.
- Add `test_pos_embed_with_cache` in `test_left_padding`.
- Add documentation for `past_kv_cache`.
- Fix type hints for some components that assume `attention_mask` has same number of tokens as input. This was previously unnoticed because there were no tests that covered `past_kv_cache`.
- Support freezing …
=> Improve attention masking and key-value caching.

.github/workflows/checks.yml, poetry.lock, pyproject.toml
Python 3.7 causes a lot of issues with dependency conflicts, and is due to reach end of life soon (2024).
Dropping so that we can simplify the install process and also use pylint.
=> Remove Python 3.7 support

transformer_lens/HookedTransformer.py, transformer_lens/utils.py
- Improve documentation for prepend_bos and padding_side in several functions in HookedTransformer and utils. It is currently unclear that they are just intended to be used as overrides of the default values set in the initial config.
- Improve the syntax of some type hints.
=> Update docs to show prepend_bos and padding_side are optional

docs/source/content/contributing.md, makefile
Note these are also added to the makefile as this is currently the approach people use to run the tests. In the future we should probably remove this as it's better to stick to one language in the repo (and a .py script file can also do all of this).
=> Add docs hot reloading instructions for contributors

tests/acceptance/test_hooked_transformer.py
Lowers the margin of error in the test `tests/acceptance/test_hooked_transformer.py` to account for recent changes to the model EleutherAI/pythia-70m, which has caused old margin of error to fail in the CI. I am not sure if there should be a more complicated change to the code base to account for this recent change, but this is an option to fix the test at least temporarily, or permanently if it is deemed accurate enough with a margin of 5e-4 instead of 5e-5.
=> Fixed current CI issues with accuracy failing for Pythia model

docs/source/conf.py, transformer_lens/loading_from_pretrained.py
I have been using TransformerLens on some models I trained using Karpathy's popular [nanogpt](https://github.com/karpathy/nanoGPT) repository. There are two complications I had to deal with:
The first is that some state dicts saved after using torch.compile() have an unwanted prefix on keys that needs to be removed. Karpathy deals with it like [this](https://github.com/karpathy/nanoGPT/blob/eba36e84649f3c6d840a93092cb779a260544d08/train.py#L171). I added this same unwanted prefix removal in the conversion function. 
The second is that the nanogpt models can be created with or without bias. By default, there is no bias. This function can handle both cases. To verify that my conversion function works as expected, I created this Colab: …
=> Add a function to convert nanogpt weights

transformer_lens/HookedTransformerConfig.py, transformer_lens/components.py, transformer_lens/loading_from_pretrained.py
This PR adds support for CodeLlama-7b series. 
Related to issue https://github.com/neelnanda-io/TransformerLens/issues/468
The changes here are relatively minor since Llama2-7b is already available in this repo. These changes include:
1. Adjust `d_vocab` according to different versions.
2. Add a new `rotary_base` parameter in `HookedTransformerConfig`.
3. Apply the changes in `HookedTransformerConfig` to `Attention` module when calling `calculate_sin_cos_rotary`
I have tested these models locally. However it might be too time-consuming to load Llama and test the model in `test_hooked_transformer.py` so I did not write tests there.
Example test case:
```python
import torch
from transformer_lens import HookedTransformer
from transformers import AutoModelForCausalLM, AutoTokenizer
MODEL_NAME …
```
=> Add support for CodeLlama-7b

transformer_lens/loading_from_pretrained.py
Caps Mistral's context length at 2k, as its default length of 32k uses a very large amount of memory.
Discussed in #490 and #491
This change will not be needed after #493, and is just to allow for Mistral to be easily used in the short term while #493 is in review. 
Fixes #490 
=> Cap Mistral's context length at 2k

transformer_lens/loading_from_pretrained.py
I recently had a pull request merged to add a function for converting nanogpt models to transformer lens format. When using some of the code, I noticed that I had a redundant assignment for the bias values in the MLP.
Lines 1863-1868 assign the same values as lines 1882-1887. In addition, the second assignment had an unused .T transpose. The transpose is unused because the bias values are 1 dimensional.
Although this shouldn't change anything, I updated my Colab notebook contained here: https://colab.research.google.com/drive/1CqMRAezkc2vVJKPiKA3Q7ACdjgzH_y7K?authuser=0#scrollTo=dqaNKBD7V4Bk
And ensured that it still produced the same results as the run from my previous pull request: https://github.com/neelnanda-io/TransformerLens/pull/475
My apologies for the oversight. …
=> Remove redundant MLP bias assignment

transformer_lens/loading_from_pretrained.py
The main changes are:
1. We check if GQA is being used by checking if `cfg.n_key_value_heads` is not None.
2. We introduce a variable `gqa_uscore` in `convert_llama_weights()` which is set to "_" if GQA is used, and an empty string otherwise. This is used to modify the state dict keys for the key and value weights and biases.
3. When rearranging the key and value projection weights (`W_K` and `W_V`), we use `cfg.n_key_value_heads` if GQA is used, otherwise we use `cfg.n_heads`.
4. We modify the state dict keys for the key and value weights and biases by appending `gqa_uscore` to the key names.
5. When creating the key and value biases (`b_K` and `b_V`), we use `cfg.n_key_value_heads` if GQA is used, otherwise we use `cfg.n_heads`.
These modifications ensure that the key and value …
=> Add support for Llama-2-70b-chat-hf

transformer_lens/utils.py
pytest is not a proper dependency of this module so importing fails.
This PR moves the skip statement to a noop in case pytest is not installed.
=> Bugfix: pytest import

transformer_lens/ActivationCache.py
The incl_mid parameter was in the documentation of decompose_resid() but it is not an actual parameter, probably copied over from accumulated_resid()
=> Remove non-existing parameter from decompose_resid() documentation

transformer_lens/FactoredMatrix.py
This should `FactoredMatrix.__matmul__` to be used in `functools.reduce` without triggering type errors.
=> Add `@overload` to `FactoredMatrix.__{,r}matmul__`

transformer_lens/components.py
A brief PR in response to #499 
This adds a comment to the AbstractAttention docstring, explaining the reasoning behind using `abstract_attribute` and linking to further documentation.
=> Improve documentation for abstract attribute

transformer_lens/ActivationCache.py
The `isinstance` check fails on non-`Slice` input: `TypeError: Subscripted generics cannot be used with class and instance checks`.
Since the check seems redundant (same thing is repeated in `Slice` constructor), removing should be fine.
=> Bugfix: remove redundant assert checks

transformer_lens/components.py
This change fixes typing problems that caused mypy issues for the 4bit-quanitized Llama PR, as discussed in #486. Concretely, it:
- changes a use of `cfg.d_mlp` to `self.cfg.d_mlp`, as only the latter's type is known to mypy
- changes the definition of `W_Q` and `W_O` in `AbstractAttention`, making them `bnb.Params4bit` if `cfg.load_in_4bit` is `True`, and `nn.Parameter` otherwise; in both cases, they're empty. It also removes the `W_Q` and `W_O` re-definitions in `Attention`.
The latter change is because `W_Q` and `W_O` were previously defined as `nn.Parameter` in `AbstractAttention` and then redefined (in `Attention`) as `bnb.Params4bit` if `cfg.load_in_4bit` was `True`. So, methods of `AbstractAttention` expected `nn.Parameter` instead of `bnb.Params4bit`. This change solves that …
=> Llama 4bit v2 typing

transformer_lens/utilities/devices.py
When selecting a device for a module, TransformerLens will no longer use `cpu:0` instead of `cpu`. This was causing issue to the `nnsight` library (see https://github.com/ndif-team/nnsight/issues/121#issuecomment-2072435262)
Fixes # https://github.com/ndif-team/nnsight/issues/121#issuecomment-2072435262
Irrelevant for such a small fix
=> Fixed device being set to cpu:0 instead of cpu

transformer_lens/components.py, transformer_lens/loading_from_pretrained.py
This adds all four current Llama 3 models and enables Llama-2-70b-hf. No dependencies required for this change (but you must have been granted access on Hugging Face to download).
I didn't add tests but I did write a sanity check:
`test.py`:
```
import transformer_lens
model = transformer_lens.HookedTransformer.from_pretrained(
"meta-llama/Meta-Llama-3-8B-Instruct"
)
prompts = [
"Hey how are you doing today?",
"Two households, both alike in dignity\n(In fair Verona, where we lay our scene),",
"The Times 03/Jan/2009",
]
for prompt in prompts:
print(prompt)
print(model.generate(prompt))
tokens = model.to_tokens(prompt)
logits, cache = model.run_with_cache(tokens, remove_batch_dim=True)
print(type(logits))
print(type(cache))
```
output:
```
(transformer-lens-py3.11) …
```
=> Add support for Llama 3 (and Llama-2-70b-hf)

README.md
Looks like the HookedSAETransformer.ipynb demo was changed to Hooked_SAE_Transformer.ipynb, also I forgot to change the branch name. This PR fixes the demo links.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
- [ x] I have not rewritten tests relating to key interfaces which would affect backward compatibility
=> Fix broken HookedSAETransformer demo links

transformer_lens/hook_points.py, transformer_lens/utils.py
There is an issue with `get_caching_hooks` where if `pos_slice` is set to `None` (the default behavior), using these hooks causes cause an assertion error (for details see #574). This is because the code actually expected `pos_slice` to be `Slice` object, even though it is typed as an `Optional[Slice]` . This change makes it so that the `pos_slice` object is converted to a `Slice` if it is not one already; it also updates the typing to indicate that `pos_slice` is a `Slice` or `SliceInput`, as in `run_with_cache`.
=> Fix Pos Slice Issue

transformer_lens/loading_from_pretrained.py
This pull request adds support for [Phi-3](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf), the latest open-weights model from Microsoft.
I have not written any new test as I've only added code to parse the config dictionary for Phi-3 and to convert Phi-3's weighs. No other part of TransformerLens has been modified.
=> Add support for Phi-3

transformer_lens/loading_from_pretrained.py
A simple code change that allows you to force TL to use `trust_remote_code=True` in its configuration. This is particularly useful when you need to use an unreferenced model with a supported architecture that requires it (e.g., m-a-p/CT-LLM-Base).
=> allow user to force trust_remote_code=true via from_pretrained kwargs

docs/make_docs.py, tests/unit/test_make_docs.py
Adds "n_kv_heads" to the Model Properties Table in the documentation. Some models use multi-query attention (which uses a single key and value head) or grouped-query attention (which uses multiple key and value heads, but less than the number of query heads). This change lets users easily see which models use these.
Fixes # https://github.com/TransformerLensOrg/TransformerLens/issues/522
**Before**
**After**
=> add n k v heads to model properties table

demos/Main_Demo.ipynb
Fixed typo in link to Exploratory_Analysis_Demo.ipynb so it opens properly in colab.
Fixed typo in link to Exploratory_Analysis_Demo.ipynb so it opens properly in colab. The original link had an errant ".com" resulting in a 403 when clicking and opening in Google Colab.
None.
Screenshots not applicable.
I have done any of the above but do not believe they apply.
=> Fix typo in Main_Demo.ipynb

tests/integration/test_match_huggingface.py, transformer_lens/components/mlp.py, transformer_lens/utilities/addmm.py, transformer_lens/utils.py
#570 has shown that there are small differences in outputs between the Huggingface implementation of models, which uses a fused add-multiply (this presumably matches the way the models were trained as well) and TransformerLens, which doesn't. It seems likely that with bigger models (e.g. Mixtral), these errors accumulate enough to be significant. This is my attempt to begin to fix the problem.
Note that we take a slight readability hit, but I believe this is worth it for correctness.
For now I've only applied this to the implemenation in `mlp.py`. There are several other places the same fix should probably be applied.
Bug fix (non-breaking change which fixes an issue)
=> Match Huggingface MLP implementation exactly.

transformer_lens/components/abstract_attention.py
The attention component was not using `b_O` for models in 4 bit precision. It looked like it was, but the statement had no effect since it was in a new line, without using `\`, and not surrounded by parenthesis. I found this out by looking at the automatic inspections generated by Pycharm.
**This was caused by the black formatter.** I had to add extra parenthesis to avoid formatting warnings. I.e., just moving `+ self.b_O` to the line above will get automatically reverted when running black.
I haven't added tests for this change (AFAIK there are not tests for 4 bit precision).
=> Fix Out bias not being summed in attention component when using 4 bit precision

tests/integration/test_hooks.py, transformer_lens/components/abstract_attention.py, transformer_lens/hook_points.py
This PR fixes a bug in v2.x.x of TransformerLens where backwards hooks were changed to use the deprecated and broken `register_backward_hook()` method instead of the correct `register_full_backward_hook()`. Before v2.x.x the correct method was used. The breaking change happened in #607, but it's not clear why this change was made.
This PR also adds a test which will not allow this regression to happen again.
Fixes #672
=> fix: fixing broken backward hooks change

transformer_lens/components/embed.py
=> Fix typo in `embed.py` docs

transformer_lens/ActivationCache.py
Adding support to RMSNorm in the apply_ln_to_stack function. It should be supported by: https://github.com/TransformerLensOrg/TransformerLens/pull/489
Fixes #472 
=> Adding RMSNorm to apply_ln_to_stack

tests/integration/test_attention_mask.py, tests/integration/test_cross_entropy_loss.py, transformer_lens/HookedTransformer.py, transformer_lens/utils.py
**Allow `attention_mask` to override the default mask in `HookedTransformer.forward()`.**
Currently the `attention_mask` argument is a footgun because it does nothing if `start_at_layer` is not `None`. One solution could be to just assert that `start_at_layer` is `None` when `attention_mask` is not `None`. But it is useful to be able to control the attention masking directly, so instead this just makes it do the thing you would expect.
**Add `attention_mask` argument to `loss_fn()` and `lm_cross_entropy_loss()` and adjust the cross entropy calculation to ignore masked (padding) tokens.**
Currently the loss calculation will be wrong if there are any padding tokens (or other masked tokens). This fixes that.
=> Improve attention masking

.github/workflows/checks.yml, demos/Patchscopes_Generation_Demo.ipynb, tests/integration/test_attention_mask.py, tests/integration/test_cross_entropy_loss.py, transformer_lens/HookedTransformer.py, transformer_lens/utils.py
=> Release 2.4.0

tests/unit/test_use_attn_result.py, transformer_lens/components/abstract_attention.py
Fixes #659 
| Before | After |
| ------ | ----- |
| <img width="900" alt="Screenshot 2024-07-08 at 12 59 00 PM" src="https://github.com/TransformerLensOrg/TransformerLens/assets/40397426/a3a64899-47f4-4074-b9f5-4edcc24dbfce"> | <img width="900" alt="Screenshot 2024-07-08 at 12 59 40 PM" src="https://github.com/TransformerLensOrg/TransformerLens/assets/40397426/75e3de97-ebe0-4a7a-837f-dcdbeafa923f"> |
- [] I have made corresponding changes to the documentation
=> removed einsum causing error when use_atten_result is enabled

transformer_lens/HookedTransformer.py
Reduces TransformerLens memory initial requirement by ~50% by revising the way models are loaded into HookedTransformer.
=> revised loading to recycle state dict

transformer_lens/HookedTransformerConfig.py
It was never recently called `weight_init_mode`
Replace `weight_init_mode` with `init_mode` in the docstring of HookedTransformerConfig
- ~I have added tests that prove my fix is effective or that my feature works~
- ~New and existing unit tests pass locally with my changes~
=> HookedTransformerConfig docs string: `weight_init_mode` => `init_mode`

transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py
Sometimes when working in resource-constrained environment it's frustrating to have to load an entire model. This is most frustrating when a model is too large to fit on a single GPU, especially when I'm only looking at the first n layers of the model.
=> Allow loading only first n layers.

.github/ISSUE_TEMPLATE/bug.md, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/loading_from_pretrained.py
=> Release 2.5

tests/integration/test_grouped_query_attention.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/components/grouped_query_attention.py, transformer_lens/components/transformer_block.py
**Background**: Normal attention layers have $N$ attention heads, each with unique query/key/value weights. In contrast, GQA has $N$ unique sets of query weights but only $M<N$ unique sets of key/value weights; thus, some of the key/value weights are shared across heads, improving efficiency. Currently, this means that while the dimensionality of `hook_k_input` and `hook_v_input` is `(batch, pos, N, d_model)` for most models, it is `(batch, pos, M, d_model)` for GQA models. This is a bit annoying if we want to edit the k/v inputs to each attention head separately, even though their weights are shared.
**Proposal**:  I have added an option, `cfg.ungroup_gqa` (default: `False`), which causes the input to be fed into `hook_k_input` and `hook_v_input` as `(batch, pos, N, d_model)`, instead of …
=> Ungrouping GQA

tests/integration/test_grouped_query_attention.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/components/grouped_query_attention.py, transformer_lens/components/transformer_block.py
Accidentally did a merge commit instead of a squash. This is the same is #713
=> Redo of #713

transformer_lens/utils.py
New version of `test_prompt` in utils, which works the same way as it did before when `answer` is a string, but when it's a list of strings then it's interpreted as a list of different answers which we compare to each other.
Note - `test_prompt` is meant to support `answer: str` consisting of multiple tokens (and it does multiple forward passes, with the tokens of `answer` being attached to the prompt at each stage). This obviously isn't compatible with passing `answers: list[str]`, so I've chosen to always crop the answers to their first token if we're passing them through as a string (in other words I assume that we only ever want to use a single multi-token answer or multiple single-token answers, but not both).
Here's what passing `answer = [" John", " Mary"]` for IOI looks like:
=> `utils.test_prompt` compares multiple prompts

tests/integration/test_grouped_query_attention.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/components/grouped_query_attention.py, transformer_lens/components/transformer_block.py
Redo of #727 to make sure the history is squashed 
=> Type hooked encoder

tests/integration/test_grouped_query_attention.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/components/grouped_query_attention.py, transformer_lens/components/transformer_block.py
* Redo of #713 (#722)
* adding option to ungroup gqa
* adding option to ungroup gqa
* updating gqa / rebasing
* Update HookedTransformerConfig.py
* formatting fix
* renaming ungroup_gqa option
* Add tests for ungroup_grouped_query_attention flag
---------
* fixed typo
---------
=> Release 2.7

README.md
Argh, Slack invites break after 400 people use them, I can't see a way around this
=> Updated broken Slack link

transformer_lens/HookedTransformer.py
This changes the type signature of `from_pretrained`, so its return type is the generic type of the base class. For example, now when we use `HookedSAETransformer.from_pretrained`, the expected return type is `HookedSAETransformer` not `HookedTransformer`.
I changed this because in my [SAE intro material](https://colab.research.google.com/drive/1ePkM8oBHIEZ2kcqAiA3waeAmz8RSdHmq#scrollTo=47O2XjSCRm-9) I was having to explicitly type-annotate as `sae: HookedSAETransformer = HookedSAETransformer.from_pretrained(...)`, and so just changing the type signature seemed like the best option.
=> `from_pretrained` has correct return type (i.e. `HookedSAETransformer.from_pretrained` returns `HookedSAETransformer`)

transformer_lens/utils.py
Add `weights_only=False` argument to `torch.load`. Starting in `torch=2.4.1`, `torch.load` prints a warning when the `weights_only` argument is not given.
The only issue here is that I get an issue if I use a version of `torch` earlier than `1.13`, and `transformer_lens` officially (according to `pyproject.toml` supports back to `1.10`. However, I couldn't use `transformer_lens` with `torch==1.10` without getting other errors, so maybe it isn't really supported anyway?
Fixes #714 
- This shouldn't be necessary since no new logic is added
=> Avoid warning in `utils.download_file_from_hf`

transformer_lens/utils.py
As stated in the docstring of the function ("Note: There is a bug when inputting very small datasets (eg, <1 batch per process) where it just outputs nothing. I'm not super sure why"), `tokenize_and_concatenate` currently cannot handle small datasets. This is because the `tokenize_function` inside `tokenize_and_concatenate` isn't producing any tokens when dealing with small datasets, i.e., the tokenization process doesn't produce any output, leading to the absence of the 'tokens' column.
Issue with small datasets:
- When the dataset is small, `full_text` may not be long enough to produce a significant number of tokens.
- `num_batches` can become zero if `num_tokens` is less than `seq_len`.
- When `num_batches` is zero, slicing and rearranging operations result in empty arrays.
Fixes # …
=> Fix the bug that tokenize_and_concatenate function not working for small dataset

transformer_lens/utils.py
=> Upstream update

transformer_lens/HookedTransformer.py
Added a warning for users to load T5 models using HookedEncoderDecoder instead of HookedTransformer, and raised a RuntimeError to stop execution and prevent further incorrect usage.
Fixes #726 
=> Add warning and halt execution for incorrect T5 model usage

tests/acceptance/test_hooked_transformer.py, tests/integration/test_kv_cache.py, transformer_lens/HookedTransformer.py, transformer_lens/components/abstract_attention.py, transformer_lens/loading_from_pretrained.py
=> Release 2.9

poetry.lock, pyproject.toml
Explicitly adds type guard as a dependency 
Fixes #785
=> added typeguard dependency

demos/Colab_Compatibility.ipynb
While using the Colab_Compatibility notebook to test some of the removals of einsum usages I did, I came across some minor bugs which this PR intends to fix. There is no specific issue this PR addresses.  The bugs in question are:
1. In the run_encoder_decoder_set function, two function calls are not on the model object but on the model name (string object) which throws an error when running this function. I fixed this by adjusting the function calls accordingly.
2. In the run_encoder_decoder_set function, the generate function is called on the HookedEncoderDecoder object, but HookedEncoderDecoder doesn't support the generate function yet. I fixed this by removing the generate function call
3. The Bert model is tested as a HookedTransformer, which is incorrect since this architecture …
=> Colab compatibility bug fixes

transformer_lens/hook_points.py
Clarifies where arguments come from a bit.
=> clarified arguments a bit for hook_points

transformer_lens/ActivationCache.py
There are known accuracy issues which are to some extent caused by the usage of einsum across large parts of the codebase. This PR removes one of these usages in the logic_attrs function in ActivationCache.py. There is no specific issue associated with this PR, although removing a lot of the einsum usages could help in removing implementation inaccuracies addressed in many issues. I have not added specific test cases for this change, but I ran all the models (except those that required authorization and the paid_cpu models) in the Colab_Compatibility notebook and have not run into any compatibility issues introduced by this change. Additionally, the changed part is executed 8 times across the unit and acceptance tests.
=> Remove einsum in logit_attrs in ActivationCache

transformer_lens/ActivationCache.py
There are known accuracy issues which are to some extent caused by the usage of einsum across large parts of the codebase. This PR removes one of these usages in the compute_head_results function in ActivationCache.py. There is no specific issue associated with this PR, although removing a lot of the einsum usages could help in removing implementation inaccuracies addressed in many issues. I have not added specific test cases for this change, but I ran all the models (except those that required authorization and the paid_cpu models) in the Colab_Compatibility notebook and have not run into any compatibility issues introduced by this change. Additionally, the changed part is executed 14 times across the unit and acceptance tests.
=> Remove einsum in compute_head_results in ActivationCache

transformer_lens/HookedTransformer.py
There are known accuracy issues which are to some extent caused by the usage of einsum across large parts of the codebase. This PR removes one of these usages in the refactor_factored_attn_matrices function in HookedTransformer.py. There is no specific issue associated with this PR, although removing a lot of the einsum usages could help in removing implementation inaccuracies addressed in many issues. I have not added specific test cases for this change, but I ran all the models (except those that required authorization and the paid_cpu models) in the Colab_Compatibility notebook and have not run into any compatibility issues introduced by this change. Additionally, the changed part is executed 56 times across the unit and acceptance tests.
=> Remove einsum usage in refactor_factored_attn_matrices in HookedTransformer

transformer_lens/SVDInterpreter.py
There are known accuracy issues which are to some extent caused by the usage of einsum across large parts of the codebase. This PR removes one of these usages in the _get_w_in_matrix function in SVDInterpreter.py. There is no specific issue associated with this PR, although removing a lot of the einsum usages could help in removing implementation inaccuracies addressed in many issues. I have not added specific test cases for this change, but I ran all the models (except those that required authorization and the paid_cpu models) in the Colab_Compatibility notebook and have not run into any compatibility issues introduced by this change. Additionally, the changed part is executed once across the unit and acceptance tests.
=> Remove einsum usage in _get_w_in_matrix in SVDInterpreter

transformer_lens/components/bert_mlm_head.py
There are known accuracy issues which are to some extent caused by the usage of einsum across large parts of the codebase. This PR removes one of these usages in the forward function of BertMLMHead. There is no specific issue associated with this PR, although removing a lot of the einsum usages could help in removing implementation inaccuracies addressed in many issues. I have not added specific test cases for this change, but I ran all the models (except those that required authorization and the paid_cpu models) in the Colab_Compatibility notebook and have not run into any compatibility issues introduced by this change. Additionally, the changed part is executed 5 times across the unit and acceptance tests.
=> Remove einsum usage in forward function of BertMLMHead

tests/unit/components/test_attention.py, transformer_lens/utilities/attention.py
There are known accuracy issues which are to some extent caused by the usage of einsum across large parts of the codebase. This PR removes one of these usages in the complex_attn_linear function in utilities/attention.py. There is no specific issue associated with this PR, although removing a lot of the einsum usages could help in removing implementation inaccuracies addressed in many issues. I ran all the models (except those that required authorization and the paid_cpu models) in the Colab_Compatibility notebook and have not run into any compatibility issues introduced by this change. Additionally, the changed part is executed 7 times across the unit and acceptance tests and I have added a little additional test case myself.
=> Remove einsum in complex_attn_linear

demos/Colab_Compatibility.ipynb, transformer_lens/loading_from_pretrained.py
Adding support for Qwen's newest model QwQ (Qwen with Questions) has been requested multiple times over the past few weeks. This PR intends to address issue #808 by adding support for this model. Since this model uses the Qwen2ForCausalLM architecture, which is already implemented in TransformerLens, adding support for this model was fairly simple.
Fixes #808 
Here is a comparison of the TransformerLens logits to the ones from HuggingFace:
```
prompt = "How many r in strawberry."
=== Logits Comparison ===
TransformerLens:
Mean: tensor(-1.2255, device='mps:0', grad_fn=<MeanBackward0>)
Std: tensor(3.0775, device='mps:0', grad_fn=<StdBackward0>)
HuggingFace:
Mean: tensor(-1.2255, device='mps:0', grad_fn=<MeanBackward0>)
Std: tensor(3.0775, device='mps:0', grad_fn=<StdBackward0>)
Max diff: …
```
=> Add support for Qwen_with_Questions

transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py
The Qwen model family does not prepend a beginning of sequence token by default. I think we should try to stick as close as possible to HuggingFace, and with the changes implemented in #775 I just had to add that prepend_bos should be set to False by default to the configuration for the Qwen models. I also fixed a little typo in the warning that is given when trying to center the unembedding with a model that uses a logit softcap.
This PR is not associated with a specific issue.
=> Set prepend_bos to false by default for Qwen models

tests/integration/test_hooks.py, transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py
When using attn_in with models that use GroupedQueryAttention, TransformerLens crashes because use_attn_in does not account for the different number of query and key/value heads when using GQA. For models with GQA use_split_qkv_input should be used instead, because it implements hooks for query, key and value heads and therefore can account for the different number of heads for each of them. This PR implements a more meaningful error message that informs the user to use split_qkv_input when working with models with GQA instead of use_attn_in.
This PR is not linked to a specific issue.
After adding a test case, it failed because of a beartype error that stated that rotary_base needs to be an integer instead of a float. I adjusted this accordingly in the configuration of google/gemma-2b
=> Throw error when using attn_in with grouped query attention

demos/T5.ipynb, tests/acceptance/test_hooked_encoder_decoder.py, transformer_lens/HookedEncoderDecoder.py
The current implementation of HookedEncoderDecoder does not support the input of strings or a list of strings to the models forward function, and also does not support a generate function. This PR addresses these limitations by implementing the following:
Automatic tokenization when input to forward function is either a string or a list of strings.
Generate function which takes either tokens or a string as an input and returns a specified number of newly generated tokens by the model.
I also adapted the T5 notebook to reflect the changes to the HookedEncoderDecoder architecture and give examples of how to use the newly introduced functionalities.
There is no specific issue attached to this PR.
=> Extend support for T5 models

demos/Colab_Compatibility.ipynb, transformer_lens/loading_from_pretrained.py, transformer_lens/pretrained/weight_conversions/phi3.py
Added the `microsoft/phi-4` model, runs out of the box, just needs to use GroupAttention abstraction and iff GroupAttention is used the model weights need to adjust dimensions.
=> Added model Phi 4

transformer_lens/hook_points.py
`HookPoint.add_hook()` contained the line:
```
full_hook.__name__ = (
hook.__repr__()
)  # annotate the `full_hook` with the string representation of the `hook` function
```
This PR instead proposes
```
if isinstance(hook, partial):
full_hook.__name__ = f"partial({hook.func.__repr__()},...)"
else:
full_hook.__name__ = hook.__repr__()
```
This isn't an issue when the hook is a regular function, but the original code can be extremely expensive when hook is a partial function that contains arguments which may be large, since calling `partial.__repr__` will call `__repr__` on all of its arguments. A very natural and common usage of hooks is to create a partial function which takes a cache object as an argument. Some of the demos in the repo do this, e.g. `Exploratory_Analysis_Demo.ipynb` has: …
=> Manually create repr for partial hooks

tests/acceptance/test_multi_gpu.py, tests/unit/utilities/test_devices.py, transformer_lens/HookedTransformer.py, transformer_lens/components/abstract_attention.py, transformer_lens/components/mlps/gated_mlp.py, transformer_lens/components/rms_norm.py, transformer_lens/components/transformer_block.py, transformer_lens/utilities/attention.py, transformer_lens/utilities/devices.py
* added new functions for determining the best available device
* added device test and integrated new function into device selection
* fixed reference
* made sure embed are still on the same device
* added log point
* added more log points
* fixed typo
* set W_E to be on the same device
* set rms norm to correct device
* set device to grouped query attention
* Revert "set device to grouped query attention"
This reverts commit 788d355cd9cff896685c711793f9b42f826ea3a9.
* Revert "set rms norm to correct device"
This reverts commit e7018c40b2ac9b6340e0b8f38cac6ffb3eba67ff.
* Revert "set W_E to be on the same device"
This reverts commit 33f443677bb1e8b61bf0c82bac558d013820a0fc.
* added debug points
* reverted most calls to new function
* reverted device list
* reverted block loop
* reverted …
=> release 2.14

transformer_lens/BertNextSentencePrediction.py, transformer_lens/HookedEncoder.py
=> fixed bert indenting

tests/unit/weight_conversion/conversion_utils/conversion_steps/test_base_weight_conversion.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_callable_weight_conversion.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_rearrange_weight_conversion.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_repeat_weight_conversion.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_terenary_weight_conversion.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_weight_conversoin_set.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_zeros_like_conversion.py, transformer_lens/factories/mlp_factory.py, transformer_lens/factories/weight_conversion_factory.py, transformer_lens/weight_conversion/conversion_utils/conversion_helpers.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/arithmetic_weight_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/base_weight_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/callable_weight_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/ternary_weight_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/types.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/weight_conversion_set.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/zeros_like_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/zeros_like_conversoin.py, transformer_lens/weight_conversion/gemma.py, transformer_lens/weight_conversion/t5.py
Adds additional tests for weight conversion components 
=> Component test coverage

transformer_lens/weight_conversion/conversion_utils/conversion_steps/rearrange_weight_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/repeat_weight_conversion.py, transformer_lens/weight_conversion/conversion_utils/conversion_steps/weight_conversion_set.py, transformer_lens/weight_conversion/gemma.py
Allows loading of Gemma and gpt in new structure
=> Bug new loading

transformer_lens/HookedTransformerConfig.py, transformer_lens/components/abstract_attention.py, transformer_lens/loading_from_pretrained.py
The current LLama3.x implementations use incorrect scaling factors for RoPE
https://github.com/huggingface/transformers/blob/3165eb7c2808832d0de86c8f508d9da6b2124044/src/transformers/modeling_rope_utils.py#L407-L410
I used this script for testing:
```python
import os
import torch
from torch.utils.data import DataLoader
from transformer_lens import HookedTransformer
from transformers import AutoModelForCausalLM
from datasets import load_dataset
torch.set_grad_enabled(False)
dtype = torch.float32
model_tl = HookedTransformer.from_pretrained_no_processing("meta-llama/Llama-3.2-1B", dtype=dtype)
model_hf = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-3.2-1B", torch_dtype=dtype)
dataset = load_dataset("EleutherAI/fineweb-edu-dedup-10b", …
```
=> Fix LLama RoPE

.github/workflows/checks.yml
=> added conditional check for hugging face

tests/acceptance/test_evals.py, tests/acceptance/test_hooked_transformer.py, tests/acceptance/test_tokenizer_special_tokens.py
=> created a seperate list of models to test for public PRs

tests/acceptance/test_multi_gpu.py, transformer_lens/utilities/devices.py
Current implementation will always load models on `cuda:0` due to the implementation of `get_best_available_cuda_device` which always enumerates devices from 0. This PR fixes the case of loading one model to specific device.
=> Fix loading on specific device

tests/integration/model_bridge/test_bridge_integration.py, tests/unit/model_bridge/test_bridge.py, tests/unit/pretrained_weight_conversions/test_neo.py, tests/unit/weight_conversion/conversion_utils/conversion_steps/test_weight_conversion_set.py, transformer_lens/HookedEncoderDecoder.py, transformer_lens/model_bridge/bridge.py, transformer_lens/model_bridge/conversion_utils/__init__.py, transformer_lens/utilities/tokenize_utils.py
=> Refactor final issues

transformer_lens/boot.py, transformer_lens/model_bridge/bridge.py
This PR properly sets up the tokenizer in the boot function such that all the previous functionality, like prepending tokens and specifying which side to use for padding, work as they used to with the old modules.
=> Setup tokenizer in boot function

transformer_lens/model_bridge/supported_architectures/mistral.py
This PR maps a Bridge to every module of Mistral thus creating hooks for every activation that happens during the forward pass in transformers.
=> Create bridges for every module in Mistral

tests/integration/model_bridge/test_bridge_integration.py, tests/unit/utilities/test_aliases.py, transformer_lens/model_bridge/bridge.py, transformer_lens/model_bridge/generalized_components/attention.py, transformer_lens/model_bridge/generalized_components/base.py, transformer_lens/model_bridge/generalized_components/block.py, transformer_lens/model_bridge/generalized_components/embedding.py, transformer_lens/model_bridge/generalized_components/mlp.py, transformer_lens/model_bridge/generalized_components/normalization.py, transformer_lens/utilities/aliases.py
=> Unified aliases

transformer_lens/model_bridge/architecture_adapter.py, transformer_lens/model_bridge/component_setup.py, transformer_lens/model_bridge/supported_architectures/mixtral.py
This PR maps a Bridge to every module of Mixtral thus creating hooks for every activation that happens during the forward pass in transformers. In order to make this possible, this PR changed the current code such that nested BlockBridges are now supported.
=> Create bridge for every module in Mixtral

tests/integration/model_bridge/test_bridge_integration.py, transformer_lens/model_bridge/sources/transformers.py
Bridge.boot should allow using alias model names, but show a deprecation warning
=> feat: Bridge.boot should allow using alias model names, but show a deprecation warning

.github/workflows/checks.yml, transformer_lens/model_bridge/bridge.py, transformer_lens/utilities/aliases.py
**Problem**
This errors:
```
from transformer_lens.model_bridge import TransformerBridge
model = TransformerBridge.boot_transformers(model_name="gemma-2-2b", device="mps", dtype="bfloat16")
model.enable_compatibility_mode()
```
Error
```
AttributeError: 'TransformerBridge' object has no attribute 'pos_embed'
```
**Cause**
We're using a hook_aliases mapping which maps hook_pos_embed to pos_embed.hook_out. But that is only valid for gpt2-style models. For gemma/llama/etc other rotary style models it should be rotary_emb.hook_out (please double check me on this!).
**Fix**
Turn hook_aliases values into a list/array if there are multiple options:
```
hook_aliases = {
"hook_embed": "embed.hook_out",
"hook_pos_embed": ["pos_embed.hook_out", "rotary_emb.hook_out"],
"hook_unembed": …
```
=> map hook_pos_embed to rotary_emb, allow hook_aliases to be a list

transformer_lens/model_bridge/supported_architectures/phi.py
=> Remove second layer norm from phi component mapping

transformer_lens/model_bridge/bridge.py
…for already initialized components
=> Properly set up normalization_type and layer_norm_folding attributes in initialized components
