TransformerLensOrg/TransformerLens

easy_transformer/EasyTransformer.py, easy_transformer/__init__.py, requirements.txt, setup.py
Added checkpointing code. Also cleaned it up to work properly with !pip install git+https://github.com/neelnanda-io/Easy-Transformer.git , added dependency requirements to setup.py and added import statements to __init__.py so `import easy_transformer` works
=> Add checkpoints

easy_transformer/EasyTransformer.py, easy_transformer/EasyTransformerConfig.py, easy_transformer/__init__.py
If this looks good, will follow up soon with from_pretrained and from_config classmethods to instantiate EasyTransformer
=> Make config dataclass and (attempt to) handle any possible downstream consequences

EasyTransformer_Demo.ipynb, easy_transformer/EasyTransformer.py, easy_transformer/__init__.py, easy_transformer/train.py, easy_transformer/weight_conversion.py
Minor fixes to config - you now import EasyTransformer and EasyTransformerConfig directly. Also fixed a bunch of bugs in the demo notebook.
=> Fix config import

EasyTransformer_Demo.ipynb, Interpreting_Sorting_Demo.ipynb, easy_transformer/EasyTransformer.py, easy_transformer/components.py, easy_transformer/weight_conversion.py, setup.py
matrix for some perf gain. Also refactored to use fancy_einsum everywhere!
=> BREAKING: Heavy refactor to use right matmuls, flip the order of every weight

EasyTransformer_Demo.ipynb, Interpreting_Sorting_Demo.ipynb, easy_transformer/EasyTransformer.py, easy_transformer/EasyTransformerConfig.py, easy_transformer/components.py, easy_transformer/utils.py
Refactored loading code - the model can now be directly initialized from
EasyTransformer(config), a state dict can be loaded via
model.load_and_process_state_dict(state_dict) and the pretrained model
parsing code was moved to from_pretrained and simplified
=> Refactored Loading Code

.gitignore, EasyTransformer_Demo.ipynb, easy_transformer/EasyTransformer.py, easy_transformer/EasyTransformerConfig.py, easy_transformer/components.py
Made a very janky change to add in shortformer attention - this makes forming induction heads much easier, cleaner and faster, by only giving the model one way to do this rather than several.
=> Shortformer attn

EasyTransformer_Demo.ipynb, easy_transformer/EasyTransformer.py, easy_transformer/components.py, easy_transformer/utils.py
=> Cache and gen

Hacky-Interactive-Lexoscope.ipynb, easy_transformer/weight_conversion.py
Added a hacky demo for how to create an interactive Lexoscope!
=> Lexoscope demo

easy_transformer/EasyTransformer.py, easy_transformer/utils.py
Added a factored matrix class to efficiently deal with low rank factorisations of matrices, and utilities to calculate composition scores
=> Composition Scores

easy_transformer/EasyTransformer.py, easy_transformer/utils.py
AFAICT there are no definitions of composition score even in Transformer Circuits. So this provides a link.
=> add reference for composition scores

poetry.lock, pyproject.toml
This is used on some older Colab notebooks.
=> Support Python 3.7

further_comments.md, transformer_lens/HookedTransformer.py
Added some additional weight processing.
b_V is now set to zero by default, and folded into b_O (it doesn't actually matter which head it's part of, since attention patterns add to 1, so it just maps to the output of the layer. But it can be a significant fraction of the head result, in a pretty misleading way).
When folding layer norm, the *reading* weights are centered - the output of LayerNormPre is mean zero, so the component in the reading matrix of the direction of all ones doesn't matter, and can be deleted.
(Credit to Zach Furman on pointing this out)
This PR passes the tests, so it hasn't broken any computation in the model!
=> Folded value biases & centered reading weights while folding LN

transformer_lens/hook_points.py, transformer_lens/tests/test_hooks.py
Addresses https://github.com/neelnanda-io/TransformerLens/issues/113
Unfortunately, I had some trouble setting up my dev environment so I was unable to confirm if the tests actually pass 😢.
If anyone who can run tests can pull this and check if this is working, that would be great. Otherwise I'll try to come back to this later.
=> Implement permanent hooks

.github/workflows/release.yml
Resolve a deprecated GitHub action warning
=> Bump ws-action-parse-semver

transformer_lens/HookedTransformer.py, transformer_lens/utils.py
Not sure if you like this - I wanted to specify data_dirs for dataset whilst using this util. Also refactored a bit.
=> let 'get_dataset' function pass kwargs

transformer_lens/HookedTransformer.py, transformer_lens/tests/test_cache_hook_names.py, transformer_lens/tests/test_hooks.py
Added a test that nothing extra was added to the default cache from run_with_cache, in response to a bug in #158
=> Test cache names

transformer_lens/HookedTransformer.py
Hello, this caught me out, so adding docs in the hope they will help somebody.
If you don't think that is helpful then feel free to close.
Many thanks!
=> Add gotcha to HookedTransformer.to_str_tokens docstring

.github/workflows/checks.yml, .gitignore, README.md, poetry.lock, pyproject.toml, setup.py
- I've added pytest-cov to the dependencies and updated tests to run with a coverage report.
Not a super essential commit now but worth doing sooner/later, especially since building comprehensive coverage is a reasonable goal for Transformer Lens.
=> Test coverage reports

.github/workflows/gh-pages.yml
So we don't have to push to a branch.
=> retarget pages at main pushes

poetry.lock, pyproject.toml
=> Run poetry lock

transformer_lens/tests/test_utils.py, transformer_lens/utils.py
=> Slice: doc and tests

transformer_lens/components.py
Addresses #157.
Clones the output of PosEmbed.
=> Clone pos embed

tests/acceptance/test_transformer_lens.py
Added a test to make sure that #157 is fixed.
=> Add pos embed hook tests

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/proposal.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
Adding templates for PRs and Issues.
=> issue and pr templates

.github/workflows/checks.yml, README.md, makefile
* Add a makefile with commands for running unit and acceptance tests
* Use the makefile commands in CI to promote consistency
* Update README
No issue.
- ~~I have commented my code, particularly in hard-to-understand areas~~
- ~~I have added tests that prove my fix is effective or that my feature works~~
=> Create makefile with test commands

tests/acceptance/test_evals.py, transformer_lens/evals.py
Implements #106.
Example usage:
```python
from transformer_lens.evals import ioi_eval, IOIDataset
from transformer_lens.HookedTransformer import HookedTransformer
model = HookedTransformer.from_pretrained('gpt2-small')
print(ioi_eval(model, num_samples=100))
ds = IOIDataset(
tokenizer=model.tokenizer,
num_samples=100,
templates=['[A] met with [B]. [B] gave the [OBJECT] to [A]'],
names=['Alice', 'Bob', 'Charlie'],
nouns={'OBJECT': ['ball', 'book']},
)
print(ioi_eval(model, dataset=ds))
ds = IOIDataset(
tokenizer=model.tokenizer,
num_samples=100,
names=['John Smith', 'John Doe'],
)
print(ioi_eval(model, dataset=ds))
ds = IOIDataset(
tokenizer=model.tokenizer,
num_samples=100,
templates=['[B] met with [A]. [A] said hello to [A]'],
)
print(ioi_eval(model, dataset=ds))
```
=> IOI Evaluation

Main_Demo.ipynb
A small fix for some grammar and typo mistakes I noticed when following the demo.
Unsure about the `add_hook` change and the IOI task change, would like some feedback on those.
Fixes # (issue) - no issue.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
=> fixing some typos/grammar in Main_Demo.ipynb

demos/Head_Detector_Demo.ipynb
Fixed Head Detection demo to install https://github.com/neelnanda-io/TransformerLens.git instead of my branch https://github.com/JayBaileyCS/TransformerLens.git that I was using for demo testing and forgot to swap out after. (Related to Issue #238 since that would fix this problem) Despite Juypter Notebook apparently thinking the entire notebook is altered, this is actually a one-line change.
=> Changed head detection demo to install correct TransformerLens branch

transformer_lens/loading_from_pretrained.py
=> Register Pythia V1 + V0 model change

transformer_lens/patching.py
In #242 I added some doc strings for some common patching functions, but not all of them. In this PR I add similar docstrings for all patching functions.
- [x ] This change requires a documentation update
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- [x ] I have made corresponding changes to the documentation
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility
=> Finish patching docs

transformer_lens/HookedTransformer.py
Delete a bunch of unused imports in HookedTransformer.py
No issue.
- Refactor
- ~I have commented my code, particularly in hard-to-understand areas~
- ~I have made corresponding changes to the documentation~
- ~have added tests that prove my fix is effective or that my feature works~
- ~New and existing unit tests pass locally with my changes~
- ~I have not rewritten tests relating to key interfaces which would affect backward compatibility~
=> Optimize imports in HookedTransformer

README.md, tests/acceptance/test_tokenizer_special_tokens.py, tests/unit/test_tokenization_methods.py, transformer_lens/HookedTransformer.py
Add tests for tokenization methods (no docs changed yet)
Fixes part of #100
=> Add tests for tokenization methods

tests/acceptance/test_hooked_transformer.py, transformer_lens/utils.py
Dumb method to free up disk space in CI.
=> Make it so we free up disk space after running each model test in the CI

tests/acceptance/test_hooked_transformer.py, tests/unit/factored_matrix/test_get_item.py, transformer_lens/FactoredMatrix.py, transformer_lens/utils.py
Fix the behaviour of FactoredMatrix.__getitem__ and add tests. It fixes a problem with the dimensions which was causing in the added tests the AssertionError :
Fixes #224 
=> FactoredMatrix __getitem__  (#224)

tests/unit/test_tokenization_methods.py, transformer_lens/HookedTransformer.py
- Move all tensors to the correct device in tests
- Move new tensor to correct device in `get_token_position()` 
Fixes #304 
=> Fix tokenization tests on GPU

tests/acceptance/test_activation_cache.py, tests/unit/test_cache_hook_names.py, tests/unit/test_hooks.py, transformer_lens/HookedTransformer.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/components.py
Updates the addition made in https://github.com/neelnanda-io/TransformerLens/pull/313 based on the comments made after the merge.
Namely, adds an optional flag for `hook_mlp_in` and a test that the conditional flag is working.
I'm not copying the boilerplate as that was covered last PR, I hope that's OK
=> Update to `hook_mlp_in`

transformer_lens/loading_from_pretrained.py
Tiny change to add some new, even smaller pythia models
=> Added tiny pythia models

tests/acceptance/test_hooked_transformer.py, transformer_lens/loading_from_pretrained.py
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] I have not rewritten tests relating to key interfaces which would affect backward compatibility
<!--
As you go through the checklist above, you can mark something as done by putting an x character in it
=> added support for pythia 160m seeds

transformer_lens/components.py
=> Bugfix attn left padding

tests/acceptance/test_patching.py
=> fixed assertion

.devcontainer/devcontainer.json, .gitignore, .vscode/extensions.json, .vscode/settings.json, pyproject.toml
A few commits (suggest we don't squash), that should help improve the code formatting over time (and improve the developer experience). These are some defaults I've been using for a while on similar projects.
Fixes #
The code is currently formatted in quite an ad-hoc way (e.g. some files have very long comment lines, others have lots of black and mypy warnings...). Ideally we'd fix this through CD checks, but that's quite a large project as it would require going through the whole codebase and making the formatting consistent. This approach will let us gradually improve things, before making a repo wide change.
=> Add developer tooling defaults & VS Code extensions

transformer_lens/ActivationCache.py, transformer_lens/FactoredMatrix.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformerConfig.py, transformer_lens/SVDInterpreter.py, transformer_lens/components.py, transformer_lens/evals.py, transformer_lens/head_detector.py, transformer_lens/hook_points.py, transformer_lens/loading_from_pretrained.py, transformer_lens/past_key_value_caching.py, transformer_lens/patching.py, transformer_lens/train.py, transformer_lens/utilities/devices.py, transformer_lens/utils.py
=> Add a summary docstring to the sub-modules

.github/workflows/rebase-pull-requests.yml
This adds a GitHub action, which will rebase all pull requests when anything is pushed to main to avoid issues where CI actions have been run on an old base while reviewing pull requests.
=> Feature auto rebase

tests/unit/test_start_at_layer.py, tests/unit/test_stop_at_layer.py, transformer_lens/HookedTransformer.py
Return the current residual when stop_at_layer is not None.
=> Return the current residual when stop_at_layer is not None.

.github/workflows/checks.yml, .github/workflows/gh-pages.yml, .vscode/settings.json, docs/make_docs.py, docs/source/conf.py, docs/source/content/citation.md, docs/source/content/development.md, docs/source/content/gallery.md, docs/source/content/getting_started.md, docs/source/content/tutorials.md, poetry.lock, pyproject.toml, transformer_lens/ActivationCache.py, transformer_lens/HookedTransformer.py, transformer_lens/SVDInterpreter.py, transformer_lens/evals.py, transformer_lens/head_detector.py, transformer_lens/hook_points.py, transformer_lens/patching.py, transformer_lens/utils.py
Fixes all warnings and will now error if new warnings are created (so we catch them in the CD).
=> Fix all Sphinx warnings

.github/workflows/checks.yml
This should add a bit of a speed boost as the checks are currently taking around 9m in total
=> Make unit & acceptance tests run in parallel

.github/workflows/gh-pages.yml
Removes node deprecated warning and speeds up poetry install.
=> Update GitHub CD Actions

README.md
- Organise in the order people usually want (e.g. description first)
- Remove the top image
- Add some buttons
- Fix all linting issues (e.g. should use * for bullets)
=> Organise & fix README

poetry.lock, pyproject.toml
This will reduce compatibility issues with Jax
=> Relax CUDA requirements

tests/acceptance/test_hooked_transformer.py
MPS has trouble with floats in the dtype test. If it passes in CI, it doesn't need to pass locally here. Could be an issue later if people are relying on local tests for this check but there are plenty of other tests so this seems worth it.
=> make tests pass mps

docs/source/content/contributing.md
Very minor change to docs. I noticed that the full test suites in the make file were not in the contributing guide, so they have been added
=> updated docs to account for additional test suites

demos/No_Position_Experiment.ipynb
Fixes the no position demo, and gets it running on current version of transformer lens
=> Demo no position fix

demos/No_Position_Experiment.ipynb, demos/Othello_GPT.ipynb
Installed torchtyping in colab in order to get the Othello demo working again
=> Othello colab fix

demos/Santa_Coder.ipynb
Fixed santa coder for curent colab, and normalized name with the rest of the demos
=> Fixed Santa Coder demo

.github/workflows/gh-pages.yml, docs/source/content/getting_started.md, transformer_lens/HookedEncoder.py, transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
Resolves issue with access to hugging face. I still need to make a couple docs changes to show how to configure a token, but the actual implementation is set.
Fixes #548
=> Hf token auth

transformer_lens/components.py, transformer_lens/loading_from_pretrained.py
Removed duplicate rearrange block
Fixes #553
=> removed deuplicate rearrange block

.github/workflows/checks.yml, makefile
Checking into why SAE tests are failing in CI
=> Resolve SAE CI Test failures

.github/workflows/checks.yml, makefile
Moved download location of artifact to be within already built docs directory.
=> Ci coverage location

.github/workflows/checks.yml, makefile, tests/acceptance/test_activation_cache.py
Fixed an issue preventing the full coverage report from being generated.
=> Ci full coverage

.github/workflows/checks.yml
Moved the download action of the test coverage report to try to see if it will upload properly.
=> moved coverage report download

.github/workflows/checks.yml
This reverts commit 983b602f8f6da66318e99bd8976ed49465f4ce61.
=> Revert "moved coverage report download (#564)"

.github/workflows/checks.yml, docs/source/index.md
Moved docs coverage link to be relative to static directory
=> moved report to static section

transformer_lens/HookedTransformer.py
Found another instance of old functionality, which has been replaced by a new centralized function.
=> unwrapped config

.github/PULL_REQUEST_TEMPLATE.md
Adds a new note to the pull request template about where things should be merged to going forward.
=> updated pull reqeust template to account for new dev branch

.github/PULL_REQUEST_TEMPLATE.md
Added a new note to hopefully get more people to merge from more verbose branches, so we can manage pending PRs without needing to submit merge PRs on their remotes.
=> updated PR template to add a note about merging from different branches

README.md
Previously the badge did not show but now does.
N/A
=> Fix docs badge in README

docs/source/content/getting_started.md, transformer_lens/loading_from_pretrained.py
Prevents error when loading Mistral 7B v0.2 Instruct
=> Add Mistral 7B v0.2 Instruct

docs/source/content/getting_started.md, transformer_lens/loading_from_pretrained.py
Reverts TransformerLensOrg/TransformerLens#579
There is an additional issue that needs to be discussed on this model
=> Revert "Add Mistral 7B v0.2 Instruct"

transformer_lens/loading_from_pretrained.py
=> Release 1.18

tests/unit/test_svd_interpreter.py
Creates a `@pytest.fixture` for some code in `test_svf_interpreters.py` that was otherwise running at the top level. In particular, when this code fails (as it did in another of my branches, due to issues with the GPU on the test runner), it aborts test collection entirely, which means I can't see any test results, even those that don't use the model.
=> More pytest fixtures

transformer_lens/loading_from_pretrained.py
**Description:**
This pull request adds support for the [`ai-forever/mGPT` model](https://huggingface.co/ai-forever/mGPT). As a multilingual language model based on the [GPT-2 architecture](https://huggingface.co/openai-community/gpt2-medium), the only additions are its name and alias.
---
=> Add support for ai-forever/mGPT model 

tests/unit/test_hooked_root_module.py, transformer_lens/hook_points.py
Simplified existing functions, merged duplicate code, and tested new functions to resolve an existing issue in 1.x and make the code easier to both test and understand.
Fixes #611
=> moved enable hook functionality to separate functions and tested new functions

transformer_lens/hook_points.py
Fixes an error in the CI introduced yesterday with a merge
=> fixed format

README.md, docs/source/content/news/release-2.0.md
Added the blog post announcement for transformer lens 2.0
=> added release blog

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/checks.yml, docs/source/index.md
Added link to news article, and made docs build when branches named docs are the origin
=> added news link

transformer_lens/loading_from_pretrained.py
The old link is dead so I found a permalink to the state of the repo as of when it was written.
=> [docs] Update Mixtral repo reference

debugging/comparing-to-huggingface.ipynb
Bryce suggested I add this since this script has been helpful in debugging the Mixtral issue.
New feature (non-breaking change which adds functionality)
=> Add comparing-to-huggingface.ipynb.

tests/acceptance/test_activation_cache.py, transformer_lens/ActivationCache.py, transformer_lens/HookedTransformer.py
I've added more tests for ActivationCache, increasing coverage from 64% to 95%. In the process I also fixed some minor bugs arising in border cases.
=> Add tests for ActivationCache

transformer_lens/pretrained/weight_conversions/mixtral.py
=> Fixed weight conversion

transformer_lens/components/abstract_attention.py
* Updated README to have Bryce as the maintainer
* Fix attention result projection
Current result projection for attention is incorrect. Type annotations would suggest that `result` isn't being summed over `head_index`, but in fact it is. I've edited the function so that it's no longer being summed over `head_index`.
Note, this bug caused the ARENA material to fail for the first transformers chapter, I've tested it and it now works.
* fix formatting with black
---------
=> Release 2.2.1

tests/integration/test_hooks.py, transformer_lens/components/abstract_attention.py, transformer_lens/hook_points.py
=> Release 2.2.2

transformer_lens/loading_from_pretrained.py
=> Added gemma-2 2b

transformer_lens/loading_from_pretrained.py
=> Added gemma-2 2b (#687)

.github/workflows/checks.yml
Removes python 3.8 from official support.
=> Python 3.8 removal

transformer_lens/loading_from_pretrained.py
=> Release v2.3.1

.github/workflows/checks.yml, demos/Patchscopes_Generation_Demo.ipynb
A demo for "Patchscopes and Generation with Patching" (also see issue #680).
I put both Patchscopes and generation with patching in the same notebook and implement the generation part using "Patchscopes' language". I demonstrate three applications mentioned in the original paper, i.e. LogitLens, Entity Description and Zero-shot Feature Extraction.
Fixes #680
=> add a demo for Patchscopes and Generation with Patching

transformer_lens/HookedEncoder.py
=> fixed typo

transformer_lens/loading_from_pretrained.py
Adds support for LLaMA 3.2. Still working on adding the whole family, but the first model is ready
=> Model llama 3.2

transformer_lens/HookedEncoder.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
=> Upstream update

docs/TransformerLens_Diagram.svg
Adds TransformerLens diagram to docs
=> add transformer diagram

.github/ISSUE_TEMPLATE/compatibility.md
=> New issue template for reporting model compatibility

.github/workflows/checks.yml
Changes where the token for hugging face is located
=> Actions token access

transformer_lens/FactoredMatrix.py
=> fixed corner param

poetry.lock, pyproject.toml
Updates our torch dependency to be able to use the most recent version
=> Updates torch to use the most recent version

.github/workflows/checks.yml
Fixes deprecation issue with CI
=> updated lock command

demos/Othello_GPT.ipynb, poetry.lock, pyproject.toml, transformer_lens/loading_from_pretrained.py
=> Phi 4 docs fix

.github/workflows/checks.yml, demos/Colab_Compatibility.ipynb, demos/Othello_GPT.ipynb, demos/T5.ipynb, poetry.lock, pyproject.toml, tests/acceptance/test_hooked_encoder_decoder.py, transformer_lens/HookedEncoderDecoder.py, transformer_lens/loading_from_pretrained.py, transformer_lens/pretrained/weight_conversions/phi3.py
=> Version 2.12

.github/workflows/checks.yml
Updates to most recent version of artifact CI actions
=> updated artifacts version

pyproject.toml, transformer_lens/HookedEncoder.py, transformer_lens/HookedEncoderDecoder.py, transformer_lens/HookedTransformer.py, transformer_lens/loading_from_pretrained.py, transformer_lens/utils.py
Makes sure to properly set the type for the token in case it is not set in PRs
=> Ci hf token empty

.github/workflows/release.yml
=> moved setup python

poetry.lock, pyproject.toml, tests/unit/test_hook_points.py, transformer_lens/hook_points.py
Allows torch >=2.5 to be installed
Fixes #857
=> removed torch ceiling

poetry.lock, pyproject.toml, tests/unit/test_hook_points.py, transformer_lens/hook_points.py
* removed torch ceiling
* fixed teswt
* removed extra prepend action
* ran format
=> Release 2.14.1

poetry.lock, pyproject.toml, tests/unit/test_hooked_root_module.py, transformer_lens/HookedEncoder.py, transformer_lens/HookedEncoderDecoder.py, transformer_lens/HookedTransformer.py, transformer_lens/components/abstract_attention.py, transformer_lens/hook_points.py, transformer_lens/loading_from_pretrained.py
=> updated mypy limit

.github/workflows/checks.yml
=> enabled actions on action pr

transformer_lens/weight_conversion/conversion_utils/conversion_steps/base_weight_conversion.py, transformer_lens/weight_conversion/gemma.py
=> Fixed test for ensuring weight conversions are provided

.github/workflows/checks.yml, README.md, poetry.lock, pyproject.toml
Drops python 3.9 support for transformer lens 3.0
=> Drop python 3.9

.github/workflows/checks.yml
=> added full hf token authentication

tests/acceptance/test_hooked_transformer.py
=> added alternative when hf token is not included

tests/acceptance/test_hooked_transformer.py
=> shrunk loss test

transformer_lens/BertNextSentencePrediction.py
One unit test failed on a fresh install - this is a minimal fix that gets all unit tests passing.
Before:
```
1 failed, 291 passed, 4 skipped, 2 warnings in 72.22s (0:01:12)
```
After:
```
292 passed, 4 skipped, 2 warnings in 60.93s (0:01:00)
```
=> Fix broken test, per issue #913

.github/workflows/checks.yml
=> fixed wrapping

.github/workflows/checks.yml
=> updated triggers to enforce secrets

.github/workflows/release.yml
=> passed secret explicitly

transformer_lens/utilities/tokenize_utils.py
=> restored tokenizer content

tests/integration/model_bridge/test_bridge_integration.py, transformer_lens/model_bridge/bridge.py
=> brought in remaining hooked transformer functions

.github/workflows/release.yml
=> Pre release version publishing

transformer_lens/model_bridge/bridge.py, transformer_lens/model_bridge/generalized_components/attention.py, transformer_lens/model_bridge/generalized_components/base.py, transformer_lens/model_bridge/generalized_components/embedding.py, transformer_lens/model_bridge/generalized_components/unembedding.py, transformer_lens/model_bridge/sources/transformers.py, transformer_lens/model_bridge/supported_architectures/gpt2.py
=> Setup deprecated hook aliases and got the majority of the main demo running properly

poetry.lock, pyproject.toml
=> removed numpy ceiling

transformer_lens/model_bridge/supported_architectures/bloom.py, transformer_lens/model_bridge/supported_architectures/gpt2.py, transformer_lens/model_bridge/supported_architectures/neox.py
This PR maps a Bridge to every module of Neox thus creating hooks for every activation that happens during the forward pass in transformers. Unfortunately I couldn't test this locally since the model is too large for my laptop to run.
=> Create bridge for every module in neox

transformer_lens/model_bridge/architecture_adapter.py, transformer_lens/model_bridge/generalized_components/base.py, transformer_lens/model_bridge/supported_architectures/neo.py
This PR maps a Bridge to every module of Neo thus creating hooks for every activation that happens during the forward pass in transformers. In order to make this possible, this PR changes the getattr code in GeneralizedComponent to allow getting attributes that are of the form attribute.attribute
=> Create bridges for every module in neo

tests/unit/model_bridge/generalized_components/test_base.py, transformer_lens/model_bridge/bridge.py, transformer_lens/model_bridge/generalized_components/base.py
=> added setters and hook utils to bridge

transformer_lens/model_bridge/sources/transformers.py, transformer_lens/model_bridge/supported_architectures/phi.py
=> Create bridge for every module in Phi 1

transformer_lens/config/TransformerLensConfig.py, transformer_lens/model_bridge/bridge.py, transformer_lens/model_bridge/sources/transformers.py
=> Add missing configuration parameters
